version: '3.8'

services:
  node_backend: 
    container_name: docker-compose
    image: docker-compose:0.0.4
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=tabmime_db
      - PGUSER=julian
      - PGPASSWORD=12345
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db: 
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=julian  
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=tabmime_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:  
  nps_data: {}




      
